import { type FormEvent, useEffect, useState } from "react";
import { ImageUp } from "lucide-react";
import { Field, Input } from "../../components/ui";
import { useEmpresaSettings, useSalvarEmpresa, useUploadLogo } from "../../hooks/useConfiguracoes";
import type { EmpresaSettings } from "../../types/configuracoes";
import { buttonPrimary, Feedback, Section } from "./shared";

const vazio: EmpresaSettings = { razao_social: "", cnpj: "", logo_path: null, endereco_origem: { cep: "", logradouro: "", numero: "", complemento: "", bairro: "", cidade: "", uf: "" } };
export function PerfilEmpresaSection() {
  const query = useEmpresaSettings(); const salvar = useSalvarEmpresa(); const logo = useUploadLogo();
  const [dados, setDados] = useState<EmpresaSettings>(vazio);
  useEffect(() => { if (query.data) setDados(query.data); }, [query.data]);
  const alterar = (campo: keyof EmpresaSettings, valor: string) => setDados((d) => ({ ...d, [campo]: valor }));
  const endereco = (campo: keyof EmpresaSettings["endereco_origem"], valor: string) => setDados((d) => ({ ...d, endereco_origem: { ...d.endereco_origem, [campo]: valor } }));
  async function submit(e: FormEvent) { e.preventDefault(); await salvar.mutateAsync(dados); }
  if (query.isLoading) return <p className="text-sm text-text-secondary">Carregando perfil...</p>;
  return <div className="space-y-4"><Section title="Perfil da empresa" description="Dados usados como origem padrão nas novas cotações e nos documentos emitidos."><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="Razão social"><Input value={dados.razao_social} onChange={(e) => alterar("razao_social", e.target.value)} /></Field><Field label="CNPJ"><Input value={dados.cnpj} onChange={(e) => alterar("cnpj", e.target.value)} placeholder="00.000.000/0000-00" /></Field><div className="md:col-span-2 grid gap-3 sm:grid-cols-3"><Field label="CEP"><Input value={dados.endereco_origem.cep} onChange={(e) => endereco("cep", e.target.value)} /></Field><Field label="Logradouro"><Input value={dados.endereco_origem.logradouro} onChange={(e) => endereco("logradouro", e.target.value)} /></Field><Field label="Número"><Input value={dados.endereco_origem.numero} onChange={(e) => endereco("numero", e.target.value)} /></Field><Field label="Complemento"><Input value={dados.endereco_origem.complemento} onChange={(e) => endereco("complemento", e.target.value)} /></Field><Field label="Bairro"><Input value={dados.endereco_origem.bairro} onChange={(e) => endereco("bairro", e.target.value)} /></Field><div className="grid grid-cols-[1fr_80px] gap-2"><Field label="Cidade"><Input value={dados.endereco_origem.cidade} onChange={(e) => endereco("cidade", e.target.value)} /></Field><Field label="UF"><Input maxLength={2} value={dados.endereco_origem.uf} onChange={(e) => endereco("uf", e.target.value.toUpperCase())} /></Field></div></div><div className="md:col-span-2 flex items-center justify-between gap-3"><Feedback error={salvar.error} success={salvar.isSuccess} /><button disabled={salvar.isPending} className={buttonPrimary}>{salvar.isPending ? "Salvando..." : "Salvar perfil"}</button></div></form></Section><Section title="Logo da empresa" description="PNG, JPG ou WEBP de até 2 MB. Será utilizada futuramente nos PDFs de cotação."><div className="flex flex-wrap items-center gap-3"><label className="inline-flex h-9 cursor-pointer items-center gap-2 rounded border border-state-info/40 px-3 text-sm text-state-info"><ImageUp size={15} /> {logo.isPending ? "Enviando..." : "Selecionar logo"}<input type="file" className="hidden" accept=".png,.jpg,.jpeg,.webp" disabled={logo.isPending} onChange={(e) => { const f=e.target.files?.[0]; if(f) logo.mutate(f); }} /></label><span className="text-xs text-text-secondary">{dados.logo_path ?? "Nenhuma logo cadastrada"}</span><Feedback error={logo.error} success={logo.isSuccess} /></div></Section></div>;
}
